"""empty message

Revision ID: 059e6b1903c2
Revises: 084b2cb458fc
Create Date: 2026-02-02 15:23:14.753237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059e6b1903c2'
down_revision = '084b2cb458fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('Character_id', sa.Integer(), nullable=True),
    sa.Column('Location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['Location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
