"""empty message

Revision ID: 244c6b704815
Revises: 24c1b54c1468
Create Date: 2026-02-03 15:10:41.358715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244c6b704815'
down_revision = '24c1b54c1468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('Character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('Location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('Location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('Character_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
