"""empty message

Revision ID: 50626cca03f5
Revises: 244c6b704815
Create Date: 2026-02-03 15:12:46.007476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50626cca03f5'
down_revision = '244c6b704815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
