"""empty message

Revision ID: 6836ad529029
Revises: 20c3cbafccbe
Create Date: 2026-02-03 12:37:13.074835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6836ad529029'
down_revision = '20c3cbafccbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_Location_id_fkey', type_='foreignkey')
        batch_op.drop_column('Location_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Location_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorite_Location_id_fkey', 'location', ['Location_id'], ['id'])

    # ### end Alembic commands ###
