"""empty message

Revision ID: 9fde2cb182ab
Revises: 6836ad529029
Create Date: 2026-02-03 12:38:18.310701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fde2cb182ab'
down_revision = '6836ad529029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['Location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Location_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
