"""empty message

Revision ID: c080e457023f
Revises: 50626cca03f5
Create Date: 2026-02-03 15:27:47.249394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c080e457023f'
down_revision = '50626cca03f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_Location_id_fkey', type_='foreignkey')
        batch_op.drop_column('Location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Location_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('favorite_Location_id_fkey', 'location', ['Location_id'], ['id'])

    op.create_table('location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('img_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('use_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='location_pkey')
    )
    # ### end Alembic commands ###
